apiVersion: 1

datasources:
  # Configuration de la source de données Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: true

  # Configuration de la source de données Loki
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    isDefault: false
    version: 1
    editable: true
