{
 "title": "Octez compact dashboard",
 "tags": [
  "tezos",
  "octez"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": "label_values(octez_version,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bootstrap status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_is_bootstrapped{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_synchronisation_status{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Chain name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "octez_version{instance=\"$node_instance\"}",
     "legendFormat": "{{ chain_name }}"
    }
   ]
  },
  {
   "title": "Node release version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "octez_version{instance=\"$node_instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Node release commit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "(label_replace(octez_version{instance=\"$node_instance\"},\"commit_hash_short\" ,\"$1\",\"commit_hash\",\"^(.{8}).*$\"))",
     "legendFormat": "{{ commit_hash_short }}"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "singlestat",
   "description": "Reflects the uptime of the monitoring of the job, not the uptime of the process.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "dtdhms",
   "valueName": "max",
   "targets": [
    {
     "expr": "time()-(process_start_time_seconds{instance=\"$node_instance\"})",
     "legendFormat": "node uptime"
    }
   ]
  },
  {
   "title": "Current head level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_validator_chain_head_level{instance=\"$node_instance\"}",
     "legendFormat": "current head level"
    }
   ]
  },
  {
   "title": "Chain levels",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "octez_validator_chain_head_cycle{instance=\"$node_instance\"}",
     "legendFormat": "Current cycle"
    },
    {
     "expr": "octez_store_caboose_level{instance=\"$node_instance\"}",
     "legendFormat": "Current caboose"
    },
    {
     "expr": "octez_store_checkpoint_level{instance=\"$node_instance\"}",
     "legendFormat": "Current checkpoint"
    },
    {
     "expr": "octez_store_savepoint_level{instance=\"$node_instance\"}",
     "legendFormat": "Current savepoint"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "table",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "octez_p2p_connections_incoming{instance=\"$node_instance\"}",
     "legendFormat": "Incomming connections"
    },
    {
     "expr": "octez_p2p_points_trusted{instance=\"$node_instance\"}",
     "legendFormat": "Trusted points"
    },
    {
     "expr": "octez_p2p_connections_private{instance=\"$node_instance\"}",
     "legendFormat": "Private points"
    }
   ]
  },
  {
   "title": "P2P total connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_connections_outgoing{instance=\"$node_instance\"}",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "octez_p2p_connections_incoming{instance=\"$node_instance\"}",
     "legendFormat": "Incoming connections"
    }
   ]
  },
  {
   "title": "Head operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"0\",instance=\"$node_instance\"}",
     "legendFormat": "Consensus"
    },
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"1\",instance=\"$node_instance\"}",
     "legendFormat": "Vote"
    },
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"2\",instance=\"$node_instance\"}",
     "legendFormat": "Anonymous"
    },
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"3\",instance=\"$node_instance\"}",
     "legendFormat": "Manager"
    }
   ]
  },
  {
   "title": "Head level history",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_head_level{instance=\"$node_instance\"}",
     "legendFormat": "Head level"
    }
   ]
  },
  {
   "title": "Block validation time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "octez_validator_block_last_finished_request_completion_timestamp{instance=\"$node_instance\"} - octez_validator_block_last_finished_request_treatment_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "Validation time"
    }
   ]
  },
  {
   "title": "Gas consumed history",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "sci" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_head_consumed_gas{instance=\"$node_instance\"}",
     "legendFormat": "Gas consumed"
    }
   ]
  },
  {
   "title": "Round history",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_head_round{instance=\"$node_instance\"}",
     "legendFormat": "Round"
    }
   ]
  },
  {
   "title": "Last written block size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "octez_store_last_written_block_size{instance=\"$node_instance\"}",
     "legendFormat": "Written block size"
    }
   ]
  },
  {
   "title": "Alternate heads count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_store_alternate_heads_count{instance=\"$node_instance\"}",
     "legendFormat": "Alternate heads count"
    }
   ]
  },
  {
   "title": "Invalid blocks mean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_store_invalid_blocks{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Branch switch count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_branch_switch_count{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Store merge time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_store_last_merge_time{instance=\"$node_instance\"}",
     "legendFormat": "Merge time"
    }
   ]
  },
  {
   "title": "Max round",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_head_round{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Blocks validation mean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_block_last_finished_request_completion_timestamp{instance=\"$node_instance\"} - octez_validator_block_last_finished_request_treatment_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "blocks validation mean"
    }
   ]
  },
  {
   "title": "Chain validator request completion",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_last_finished_request_completion_timestamp{instance=\"$node_instance\"} - octez_validator_chain_last_finished_request_treatment_timestamp{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Peer validators errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_peer_system_error{instance=\"$node_instance\"}"
    },
    {
     "expr": "octez_validator_peer_too_short_locator{instance=\"$node_instance\"}"
    },
    {
     "expr": "octez_validator_peer_unavailable_protocol{instance=\"$node_instance\"}"
    },
    {
     "expr": "octez_validator_peer_unknown_ancestor{instance=\"$node_instance\"}"
    },
    {
     "expr": "octez_validator_peer_unknown_error{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Incoming connections mean",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_p2p_connections_incoming{instance=\"$node_instance\"}"
    }
   ]
  }
 ]
}