{
 "title": "Octez basic dashboard",
 "tags": [
  "tezos",
  "octez"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node_instance",
    "label": "Node instance",
    "query": "label_values(octez_version,instance)"
   }
  ]
 },
 "panels": [
  { "title": "Node stats", "type": "row" },
  {
   "title": "Bootstrap status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_is_bootstrapped{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "octez_validator_chain_synchronisation_status{instance=\"$node_instance\"}"
    }
   ]
  },
  {
   "title": "Chain name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "octez_version{instance=\"$node_instance\"}",
     "legendFormat": "{{ chain_name }}"
    }
   ]
  },
  {
   "title": "Node release version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "octez_version{instance=\"$node_instance\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Node release commit",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "(label_replace(octez_version{instance=\"$node_instance\"},\"commit_hash_short\" ,\"$1\",\"commit_hash\",\"^(.{8}).*$\"))",
     "legendFormat": "{{ commit_hash_short }}"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "singlestat",
   "description": "Reflects the uptime of the monitoring of the job, not the uptime of the process.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "dtdhms",
   "valueName": "max",
   "targets": [
    {
     "expr": "time()-(process_start_time_seconds{instance=\"$node_instance\"})",
     "legendFormat": "node uptime"
    }
   ]
  },
  {
   "title": "Current head level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_validator_chain_head_level{instance=\"$node_instance\"}",
     "legendFormat": "current head level"
    }
   ]
  },
  {
   "title": "P2p version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "octez_version{instance=\"$node_instance\"}",
     "legendFormat": "{{ p2p_version }}"
    }
   ]
  },
  {
   "title": "Distributed db version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 10 },
   "format": "none",
   "valueName": "value",
   "targets": [
    {
     "expr": "octez_version{instance=\"$node_instance\"}",
     "legendFormat": "{{ distributed_db_version }}"
    }
   ]
  },
  {
   "title": "Current savepoint level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_store_savepoint_level{instance=\"$node_instance\"}",
     "legendFormat": "current savepoint"
    }
   ]
  },
  {
   "title": "Current checkpoint level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_store_checkpoint_level{instance=\"$node_instance\"}",
     "legendFormat": "current checkpoint"
    }
   ]
  },
  {
   "title": "Current caboose level",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_store_caboose_level{instance=\"$node_instance\"}",
     "legendFormat": "current caboose"
    }
   ]
  },
  {
   "title": "Current cycle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 16 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "octez_validator_chain_head_cycle{instance=\"$node_instance\"}",
     "legendFormat": "Current cycle"
    }
   ]
  },
  {
   "title": "Trusted points",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "octez_p2p_points_trusted{instance=\"$node_instance\"}",
     "legendFormat": "trusted points"
    }
   ]
  },
  {
   "title": "Private Connections",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "octez_p2p_connections_private{instance=\"$node_instance\"}",
     "legendFormat": "Private Connections"
    }
   ]
  },
  {
   "title": "Head level history",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_head_level{instance=\"$node_instance\"}",
     "legendFormat": "Head level"
    }
   ]
  },
  {
   "title": "Block validation time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "octez_validator_block_last_finished_request_completion_timestamp{instance=\"$node_instance\"} - octez_validator_block_last_finished_request_treatment_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "Validation time"
    }
   ]
  },
  {
   "title": "Head operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"0\",instance=\"$node_instance\"}",
     "legendFormat": "Consensus"
    },
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"1\",instance=\"$node_instance\"}",
     "legendFormat": "Vote"
    },
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"2\",instance=\"$node_instance\"}",
     "legendFormat": "Anonymous"
    },
    {
     "expr": "octez_validator_block_operations_per_pass{pass_id=\"3\",instance=\"$node_instance\"}",
     "legendFormat": "Manager"
    }
   ]
  },
  {
   "title": "Gas consumed history",
   "type": "graph",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "sci" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_head_consumed_gas{instance=\"$node_instance\"}",
     "legendFormat": "Gas consumed"
    }
   ]
  },
  {
   "title": "Invalid blocks history",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_store_invalid_blocks{instance=\"$node_instance\"}",
     "legendFormat": "Invalid blocks"
    }
   ]
  },
  {
   "title": "Round history",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_head_round{instance=\"$node_instance\"}",
     "legendFormat": "Round"
    }
   ]
  },
  {
   "title": "Last written block size",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "octez_store_last_written_block_size{instance=\"$node_instance\"}",
     "legendFormat": "Written block size"
    }
   ]
  },
  {
   "title": "Store merge time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "octez_store_last_merge_time{instance=\"$node_instance\"}",
     "legendFormat": "Merge time"
    }
   ]
  },
  { "title": "P2P stats", "type": "row", "gridPos": { "h": 0, "w": 8, "x": 0, "y": 39 } },
  {
   "title": "Mempool status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_mempool_pending_validated{instance=\"$node_instance\"}",
     "legendFormat": "Validated"
    },
    {
     "expr": "octez_mempool_pending_refused{instance=\"$node_instance\"}",
     "legendFormat": "Refused"
    },
    {
     "expr": "octez_mempool_pending_outdated{instance=\"$node_instance\"}",
     "legendFormat": "Outdated"
    },
    {
     "expr": "octez_mempool_pending_branch_refused{instance=\"$node_instance\"}",
     "legendFormat": "Branch refused"
    },
    {
     "expr": "octez_mempool_pending_branch_delayed{instance=\"$node_instance\"}",
     "legendFormat": "Branch delayed"
    },
    {
     "expr": "octez_mempool_pending_unprocessed{instance=\"$node_instance\"}",
     "legendFormat": "Unprocessed"
    }
   ]
  },
  {
   "title": "P2P total connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_connections_outgoing{instance=\"$node_instance\"}",
     "legendFormat": "Outgoing connections"
    },
    {
     "expr": "octez_p2p_connections_incoming{instance=\"$node_instance\"}",
     "legendFormat": "Incoming connections"
    }
   ]
  },
  {
   "title": "P2P peers connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_peers_disconnected{instance=\"$node_instance\"}",
     "legendFormat": "Disconnected peers"
    },
    {
     "expr": "octez_p2p_peers_running{instance=\"$node_instance\"}",
     "legendFormat": "Running peers"
    },
    {
     "expr": "octez_p2p_points_greylisted{instance=\"$node_instance\"}",
     "legendFormat": "Waiting to reconnect"
    }
   ]
  },
  {
   "title": "P2P points connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_p2p_points_disconnected{instance=\"$node_instance\"}",
     "legendFormat": "Disconnected points"
    },
    {
     "expr": "octez_p2p_points_running{instance=\"$node_instance\"}",
     "legendFormat": "Running points"
    },
    {
     "expr": "octez_p2p_points_trusted{instance=\"$node_instance\"}",
     "legendFormat": "Trusted points"
    }
   ]
  },
  {
   "title": "DDB current head messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_current_head_messages{action=\"broadcasted\",instance=\"$node_instance\"}",
     "legendFormat": "get current head broadcasted"
    },
    {
     "expr": "octez_distributed_db_message_get_current_head_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get current head sent"
    },
    {
     "expr": "octez_distributed_db_message_current_head_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "current head received"
    },
    {
     "expr": "octez_distributed_db_message_get_current_head_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get current head received"
    },
    {
     "expr": "octez_distributed_db_message_current_head_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "current head sent"
    },
    {
     "expr": "octez_distributed_db_message_current_head_messages{action=\"broadcasted\",instance=\"$node_instance\"}",
     "legendFormat": "current head broadcasted"
    }
   ]
  },
  {
   "title": "DDB current branch messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_current_branch_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get current branch sent"
    },
    {
     "expr": "octez_distributed_db_message_current_branch_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "current branch received"
    },
    {
     "expr": "octez_distributed_db_message_get_current_branch_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get current branch received"
    },
    {
     "expr": "octez_distributed_db_message_current_branch_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "current branch sent"
    }
   ]
  },
  {
   "title": "DDB block headers messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_block_headers_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get block headers sent"
    },
    {
     "expr": "octez_distributed_db_message_block_header_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "block header received"
    },
    {
     "expr": "octez_distributed_db_message_get_block_headers_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get block headers received"
    },
    {
     "expr": "octez_distributed_db_message_block_header_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "block header sent"
    }
   ]
  },
  {
   "title": "DDB predecessor header messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 55 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_predecessor_header_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get predecessor header sent"
    },
    {
     "expr": "octez_distributed_db_message_predecessor_header_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "predecessor header received"
    },
    {
     "expr": "octez_distributed_db_message_get_predecessor_header_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get predecessor header received"
    },
    {
     "expr": "octez_distributed_db_message_predecessor_header_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "predecessor header sent"
    }
   ]
  },
  {
   "title": "DDB operations messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_operations_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get operations sent"
    },
    {
     "expr": "octez_distributed_db_message_operation_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "operation received"
    },
    {
     "expr": "octez_distributed_db_message_get_operations_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get operations received"
    },
    {
     "expr": "octez_distributed_db_message_operation_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "operation sent"
    }
   ]
  },
  {
   "title": "DDB operations for blocks messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_operations_for_blocks_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get ops for blocks sent"
    },
    {
     "expr": "octez_distributed_db_message_operations_for_block_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "ops for block received"
    },
    {
     "expr": "octez_distributed_db_message_get_operations_for_blocks_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get ops for blocks received"
    },
    {
     "expr": "octez_distributed_db_message_operations_for_block_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "ops for block sent"
    }
   ]
  },
  {
   "title": "DDB protocols messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_protocols_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get protocols sent"
    },
    {
     "expr": "octez_distributed_db_message_protocol_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "protocol received"
    },
    {
     "expr": "octez_distributed_db_message_get_protocols_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get protocols received"
    },
    {
     "expr": "octez_distributed_db_message_protocol_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "protocol sent"
    }
   ]
  },
  {
   "title": "DDB protocol branch messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_protocol_branch_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get protocol branch sent"
    },
    {
     "expr": "octez_distributed_db_message_protocol_branch_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "protocol branch received"
    },
    {
     "expr": "octez_distributed_db_message_get_protocol_branch_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get protocol branch received"
    },
    {
     "expr": "octez_distributed_db_message_protocol_branch_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "protocol branch sent"
    }
   ]
  },
  {
   "title": "DDB checkpoint messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_checkpoint_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get checkpoint sent"
    },
    {
     "expr": "octez_distributed_db_message_checkpoint_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "checkpoint received"
    },
    {
     "expr": "octez_distributed_db_message_get_checkpoint_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get checkpoint received"
    },
    {
     "expr": "octez_distributed_db_message_checkpoint_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "checkpoint sent"
    }
   ]
  },
  {
   "title": "DDB deactivate messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 63 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_message_get_deactivate_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "get deactivate sent"
    },
    {
     "expr": "octez_distributed_db_message_deactivate_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "deactivate received"
    },
    {
     "expr": "octez_distributed_db_message_get_deactivate_messages{action=\"received\",instance=\"$node_instance\"}",
     "legendFormat": "get deactivate received"
    },
    {
     "expr": "octez_distributed_db_message_deactivate_messages{action=\"sent\",instance=\"$node_instance\"}",
     "legendFormat": "deactivate sent"
    }
   ]
  },
  { "title": "Workers stats", "type": "row", "gridPos": { "h": 0, "w": 8, "x": 0, "y": 72 } },
  {
   "title": "Validation workers requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_block_worker_request_count{instance=\"$node_instance\"}",
     "legendFormat": "Block validator request count"
    },
    {
     "expr": "octez_validator_block_worker_completion_count{instance=\"$node_instance\"}",
     "legendFormat": "Block validator completion count"
    },
    {
     "expr": "octez_validator_block_worker_request_error_count{instance=\"$node_instance\"}",
     "legendFormat": "Block validator error count"
    },
    {
     "expr": "octez_validator_chain_worker_request_count{instance=\"$node_instance\"}",
     "legendFormat": "Chain validator request count"
    },
    {
     "expr": "octez_validator_chain_worker_completion_count{instance=\"$node_instance\"}",
     "legendFormat": "Chain validator completion count"
    },
    {
     "expr": "octez_validator_chain_worker_error_count{instance=\"$node_instance\"}",
     "legendFormat": "Chain validator error count"
    },
    {
     "expr": "octez_mempool_worker_request_count{instance=\"$node_instance\"}",
     "legendFormat": "Prevalidator validator request count"
    },
    {
     "expr": "octez_mempool_worker_completion_count{instance=\"$node_instance\"}",
     "legendFormat": "Prevalidator validator completion count"
    },
    {
     "expr": "octez_mempool_worker_error_count{instance=\"$node_instance\"}",
     "legendFormat": "Prevalidator validator error count"
    }
   ]
  },
  {
   "title": "DDB Workers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_distributed_db_requester_table_length{requester_kind=\"block_header\",instance=\"$node_instance\"}",
     "legendFormat": "headers table"
    },
    {
     "expr": "octez_distributed_db_requester_scheduler_length{requester_kind=\"block_header\",instance=\"$node_instance\"}",
     "legendFormat": "headers scheduler"
    },
    {
     "expr": "octez_distributed_db_requester_table_length{requester_kind=\"operations\",instance=\"$node_instance\"}",
     "legendFormat": "operations table"
    },
    {
     "expr": "octez_distributed_db_requester_scheduler_length{requester_kind=\"operations\",instance=\"$node_instance\"}",
     "legendFormat": "operations scheduler"
    },
    {
     "expr": "octez_distributed_db_requester_table_length{requester_kind=\"operation\",instance=\"$node_instance\"}",
     "legendFormat": "operation table"
    },
    {
     "expr": "octez_distributed_db_requester_scheduler_length{requester_kind=\"operation\",instance=\"$node_instance\"}",
     "legendFormat": "operation scheduler"
    }
   ]
  },
  {
   "title": "Validators Requests Treatments",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_last_finished_request_treatment_timestamp{instance=\"$node_instance\"} - octez_validator_chain_last_finished_request_push_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "chain validator"
    },
    {
     "expr": "octez_validator_block_last_finished_request_treatment_timestamp{instance=\"$node_instance\"} - octez_validator_block_last_finished_request_push_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "block validator"
    }
   ]
  },
  {
   "title": "Validators Requests Completion",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "octez_validator_chain_last_finished_request_completion_timestamp{instance=\"$node_instance\"} - octez_validator_chain_last_finished_request_treatment_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "chain validator"
    },
    {
     "expr": "octez_validator_block_last_finished_request_completion_timestamp{instance=\"$node_instance\"} - octez_validator_block_last_finished_request_treatment_timestamp{instance=\"$node_instance\"}",
     "legendFormat": "block validator"
    }
   ]
  },
  {
   "title": "Peer validators",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "octez_validator_peer_connections{instance=\"$node_instance\"}",
     "legendFormat": "connections"
    },
    {
     "expr": "octez_validator_peer_invalid_block{instance=\"$node_instance\"}",
     "legendFormat": "invalid blocks"
    },
    {
     "expr": "octez_validator_peer_invalid_locator{instance=\"$node_instance\"}",
     "legendFormat": "invalid locator"
    },
    {
     "expr": "octez_validator_peer_new_branch_completed{instance=\"$node_instance\"}",
     "legendFormat": "new branch completed"
    },
    {
     "expr": "octez_validator_peer_new_head_completed{instance=\"$node_instance\"}",
     "legendFormat": "new head completed"
    },
    {
     "expr": "octez_validator_peer_on_no_request_count{instance=\"$node_instance\"}",
     "legendFormat": "on no request count"
    },
    {
     "expr": "octez_validator_peer_operations_fetching_canceled_new_branch{instance=\"$node_instance\"}",
     "legendFormat": "fetching canceled new branch"
    },
    {
     "expr": "octez_validator_peer_operations_fetching_canceled_new_known_valid_head{instance=\"$node_instance\"}",
     "legendFormat": "fetching canceled new known valid head"
    },
    {
     "expr": "octez_validator_peer_operations_fetching_canceled_new_unknown_head{instance=\"$node_instance\"}",
     "legendFormat": "fetching canceled knew unknown head"
    },
    {
     "expr": "octez_validator_peer_system_error{instance=\"$node_instance\"}",
     "legendFormat": "system error"
    },
    {
     "expr": "octez_validator_peer_too_short_locator{instance=\"$node_instance\"}",
     "legendFormat": "too short locator"
    },
    {
     "expr": "octez_validator_peer_unavailable_protocol{instance=\"$node_instance\"}",
     "legendFormat": "unavailable protocol"
    },
    {
     "expr": "octez_validator_peer_unknown_ancestor{instance=\"$node_instance\"}",
     "legendFormat": "unknown ancestor"
    },
    {
     "expr": "octez_validator_peer_unknown_error{instance=\"$node_instance\"}",
     "legendFormat": "unknown error"
    }
   ]
  },
  { "title": "RPC", "type": "row", "gridPos": { "h": 16, "w": 8, "x": 0, "y": 97 } },
  {
   "title": "RPC calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/chains/<chain_id>/.*',instance=\"$node_instance\"})",
     "legendFormat": "Chains"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/chains/<chain_id>/blocks/.*',instance=\"$node_instance\"})",
     "legendFormat": "Blocks"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/version.*',instance=\"$node_instance\"})",
     "legendFormat": "Versions"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/config.*',instance=\"$node_instance\"})",
     "legendFormat": "Config"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/network.*',instance=\"$node_instance\"})",
     "legendFormat": "Network"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/workers.*',instance=\"$node_instance\"})",
     "legendFormat": "Workers"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/injection.*',instance=\"$node_instance\"})",
     "legendFormat": "Injection"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/protocols.*',instance=\"$node_instance\"})",
     "legendFormat": "Protocols"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/private.*',instance=\"$node_instance\"})",
     "legendFormat": "Private"
    },
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'/(fetch_protocol|stats|monitor)*.',instance=\"$node_instance\"})",
     "legendFormat": "Misc"
    }
   ]
  },
  {
   "title": "RPC durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/chains/<chain_id>/.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/chains/<chain_id>/.*',instance=\"$node_instance\"})",
     "legendFormat": "Chains"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/chains/<chain_id>/blocks/.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/chains/<chain_id>/blocks/.*',instance=\"$node_instance\"})",
     "legendFormat": "Blocks"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/version.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/version.*',instance=\"$node_instance\"})",
     "legendFormat": "Versions"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/config.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/config.*',instance=\"$node_instance\"})",
     "legendFormat": "Config"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/network.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/network.*',instance=\"$node_instance\"})",
     "legendFormat": "Network"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/workers.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/workers.*',instance=\"$node_instance\"})",
     "legendFormat": "Workers"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/injection.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/injection.*',instance=\"$node_instance\"})",
     "legendFormat": "Injection"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/protocols.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/protocols.*',instance=\"$node_instance\"})",
     "legendFormat": "Protocols"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/private.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/private.*',instance=\"$node_instance\"})",
     "legendFormat": "Private"
    },
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'/(fetch_protocol|stats|monitor)*.',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'/(fetch_protocol|stats|monitor)*.',instance=\"$node_instance\"})",
     "legendFormat": "Misc"
    }
   ]
  },
  {
   "title": "Total of RPC calls",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(octez_rpc_calls_count{endpoint=~'.*',instance=\"$node_instance\"})",
     "legendFormat": "total calls"
    }
   ]
  },
  {
   "title": "RPC calls rate per hour",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(octez_rpc_calls_count{endpoint=~\".*\",instance=\"$node_instance\"}[1h]))",
     "legendFormat": "calls rate"
    }
   ]
  },
  {
   "title": "Average of calls durations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'.*',instance=\"$node_instance\"})/sum(octez_rpc_calls_count{endpoint=~'.*',instance=\"$node_instance\"})",
     "legendFormat": "average duration"
    }
   ]
  },
  {
   "title": "Max of average calls durations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(octez_rpc_calls_sum{instance=\"$node_instance\"} / octez_rpc_calls_count{instance=\"$node_instance\"})",
     "legendFormat": "max average duration"
    }
   ]
  },
  {
   "title": "Max of total calls durations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(octez_rpc_calls_sum{instance=\"$node_instance\"})",
     "legendFormat": "max total duration"
    }
   ]
  },
  {
   "title": "Total of RPC calls duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(octez_rpc_calls_sum{endpoint=~'.*',instance=\"$node_instance\"})",
     "legendFormat": "total duration"
    }
   ]
  },
  { "title": "Miscellaneous", "type": "row", "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 } },
  {
   "title": "GC maintenance operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "ocaml_gc_minor_collections{instance=\"$node_instance\"}",
     "legendFormat": "Minor collections"
    },
    {
     "expr": "ocaml_gc_major_collections{instance=\"$node_instance\"}",
     "legendFormat": "Major collections"
    },
    {
     "expr": "ocaml_gc_forced_major_collections{instance=\"$node_instance\"}",
     "legendFormat": "Forced major collections"
    },
    {
     "expr": "ocaml_gc_compactions{instance=\"$node_instance\"}",
     "legendFormat": "Heap compactions"
    }
   ]
  },
  {
   "title": "GC major word sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ocaml_gc_heap_words{instance=\"$node_instance\"}* 8",
     "legendFormat": "Major heap"
    }
   ]
  }
 ]
}